let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "arepa de huevo",
      price: 25000,
      desc: "Sabrosas arepas rellenas con huevo y otros ingredientes frescos",
      longdesc: "<span>Sumérgete </span> en la auténtica delicia colombiana con nuestra Arepa de Huevo. Una mezcla perfecta de masa de maíz suave, frita a la perfección, que abraza un huevo jugoso en su interior. Una explosión de sabores que te transporta directamente a las calles de Colombia. ¡Disfruta de la auténtica esencia en cada bocado!",
      img: "images/menu/arepadehuevo.png",
      gal1: "images/menu/arepadehuevo1.png",
      gal2: "images/menu/arepadehuevo2.png",
      gal3: "images/menu/arepadehuevo3.png",
    },
    {
      id: "ioytrhndcv",
      name: "arroz con coco",
      price: 31000,
      desc: "Una delicia colombiana con arroz jugoso y leche de coco",
      longdesc: "<span>Viaja</span> a las costas colombianas con nuestro irresistible Arroz con Coco. La mezcla perfecta de arroz suculento cocido en leche de coco, que despierta tus sentidos con cada tenedor. Sumérgete en la riqueza de sabores caribeños, una experiencia gastronómica que te transporta directamente a la calidez de Colombia.",
      img: "images/menu/arrozconcoco.png",
      gal1: "images/menu/arrozconcoco1.png",
      gal2: "images/menu/arrozconcoco2.png",
      gal3: "images/menu/arrozconcoco3.png",
    },
    {
      id: "wuefbncxbsn",
      name: "arroz con leche",
      price: 29000,
      desc: "Arroz cremoso, canela y dulce leche condensada en una deliciosa combinación",
      longdesc: "<span>Explora</span> el reconfortante sabor de nuestra Arroz con Leche, un clásico que acaricia tu paladar con cada cucharada. La mezcla perfecta de arroz cremoso, canela y dulce leche condensada, esta delicia te envuelve en la calidez de tradiciones culinarias.",
      img: "images/menu/arrozconleche.png",
      gal1: "images/menu/arrozconleche1.png",
      gal2: "images/menu/arrozconleche2.png",
      gal3: "images/menu/arrozconleche3.png",
    },
    {
      id: "thyfhcbcv",
      name: "avena",
      price: 15000,
      desc: "Una mezcla cremosa y nutritiva que te envuelve en cada sorbo",
      longdesc: "<span>Refresca</span> tu día con nuestra Avena, una bebida reconfortante que combina la suavidad de la avena con la dulzura justa. Disfruta de este elixir cremoso y nutritivo que revitaliza tu energía. Cada sorbo es una experiencia única, transportándote a la autenticidad de los sabores que solo nuestra Avena puede ofrecer. ",
      img: "images/menu/avena.png",
      gal1: "images/menu/avena1.png",
      gal2: "images/menu/avena2.png",
      gal3: "images/menu/avena3.png",
    },
    {
      id: "thiecbawdjksadjk",
      name: "cazuela",
      price: 40000,
      desc: "Carnes y vegetales cocidos a la perfección en una exquisita mezcla de hierbas y especias",
      longdesc: "<span>Con la mezcla </span> perfecta de tiernas carnes, vegetales frescos y especias que dan vida a cada bocado. Este plato, cocido con esmero, te invita a disfrutar de la auténtica fusión de ingredientes que define la riqueza de la cocina colombiana. Déjate llevar por la calidez y la sazón de nuestra Cazuela, una experiencia que celebra la abundancia y el deleite en cada cucharada.",
      img: "images/menu/cazuela.png",
      gal1: "images/menu/cazuela1.png",
      gal2: "images/menu/cazuela2.png",
      gal3: "images/menu/cazuela3.png",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "fritanga",
      price: 40000,
      desc: "Carne, plátanos y arepas fritas para una experiencia irresistible.",
      longdesc: "<span> Embárcate </span> en un festín de sabores con nuestra Fritanga, una experiencia gastronómica que despierta tus sentidos. Cada bocado es una explosión de texturas y sabores auténticos, desde las carnes jugosas hasta los plátanos dorados y las arepas crujientes. Descubre el placer de una verdadera fiesta culinaria con esta selección irresistible de delicias fritas.",
      img: "images/menu/fritanga.png",
      gal1: "images/menu/fritanga1.png",
      gal2: "images/menu/fritanga2.png",
      gal3: "images/menu/fritanga3.png",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "ceviche",
      price: 54000,
      desc: "Pescado, cítricos y especias, creando una experiencia refrescante",
      longdesc: "<span> Disfruta </span> de nuestro Ceviche, una opción refrescante que combina sabores sutiles en cada bocado. Preparado con ingredientes seleccionados, este plato te invita a explorar la armonía de texturas y la frescura de la cocina. Una opción ligera y sabrosa que deleitará tu paladar con su simplicidad y encanto.",
      img: "images/menu/ceviche.png",
      gal1: "images/menu/ceviche1.png",
      gal2: "images/menu/ceviche2.png",
      gal3: "images/menu/ceviche3.png",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "limonada de coco",
      price: 16000,
      desc: "Refrescante bebida tropical con limón y coco",
      longdesc: "<span>Refresca </span> tu día con nuestra Limonada de Coco, una bebida tropical que te transportará a paraísos exóticos. La fusión perfecta de la acidez del limón y la suavidad del coco crea una experiencia refrescante y deliciosa. Descubre la armonía de sabores en cada sorbo, donde la frescura se encuentra con la dulzura tropical.",
      img: "images/menu/limonada.png",
      gal1: "images/menu/limonada1.png",
      gal2: "images/menu/limonada2.png",
      gal3: "images/menu/limonada3.png",
    },
    {
      id: "cbvxbcvsceldk",
      name: "cocadas",
      price: 40500,
      desc: "Un placer de coco y azúcar para disfrutar el auténtico sabor caribeño",
      longdesc: "<span>Deléitate</span> con nuestras Cocadas, pequeñas porciones de éxtasis tropical en cada bocado. Estos dulces exquisitos, hechos con coco y azúcar, te transportarán a playas soleadas con su sabor auténtico. Disfruta de la suavidad y la dulzura de estas delicias artesanales que capturan la esencia misma de la indulgencia caribeña.",
      img: "images/menu/cocadas.png",
      gal1: "images/menu/cocadas1.png",
      gal2: "images/menu/cocadas2.png",
      gal3: "images/menu/cocadas3.png",
    },
    {
      id: "oiopijmjkhuihb",
      name: "patacones",
      price: 25500,
      desc: "Crujientes tajadas de plátano verde frito",
      longdesc: "<span>Patacones,</span> una experiencia crujiente que despierta tus sentidos. Estas tajadas de plátano verde, fritas a la perfección, te invitan a disfrutar de la textura dorada por fuera y tierna por dentro. Perfectos como aperitivo o acompañamiento, nuestros Patacones capturan el sabor de la tradición culinaria costeña.",
      img: "images/menu/patacones.png",
      gal1: "images/menu/patacones1.png",
      gal2: "images/menu/patacones2.png",
      gal3: "images/menu/patacones3.png",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "yuca frita con suero costeño",
      price: 25000,
      desc: "Una combinación perfecta de yuca dorada y suero costeño",
      longdesc: "<span>Explora </span> la deliciosa fusión de sabores con nuestras Yuca Frita con Suero Costeño, una experiencia que combina lo crujiente y lo cremoso en cada bocado. Las tajadas de yuca, fritas a la perfección, se complementan con el toque único del suero costeño, creando un placer culinario que refleja la riqueza de la región.",
      img: "images/menu/yucasuero.png",
      gal1: "images/menu/yucasuero1.png",
      gal2: "images/menu/yucasuero2.png",
      gal3: "images/menu/yucasuero3.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
    name: "sancocho",
    price: 350000,
    desc: "Carnes, vegetales y especias, que te envuelve en su sabor reconfortante y tradicional",
    longdesc: "<span>Esta mezcla magistral </span> de carnes tiernas, vegetales frescos y especias cuidadosamente seleccionadas te invita a disfrutar de la auténtica calidez y sabor. Cada cucharada es un deleite que evoca tradiciones arraigadas, creando una experiencia gastronómica que reconforta el alma.",
    img: "images/menu/sancocho.png",
    gal1: "images/menu/sancocho1.png",
    gal2: "images/menu/sancocho2.png",
    gal3: "images/menu/sancocho3.png",
  },
  ];